# Generated by Django 5.0.3 on 2024-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category_image", models.ImageField(upload_to="upload/category/")),
            ],
        ),
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, unique=True
            ),
        ),
    ]
